eks_cluster_version                        = "1.32"
aws_load_balancer_controller_chart_version = "1.13.2"
external_dns_chart_version                 = "1.16.1"
metrics_server_chart_version               = "3.12.2"
ingress_nginx_chart_version                = "4.12.2"
